local screen=assert(io.open('../screens/graphics_editor.lua','rb')):read('*a')
local presenter=assert(io.open('../ui/menu_presenter.lua','rb')):read('*a')
assert(screen:find('popupW=610,popupH=860',1,true) and screen:find('popupResize=nil',1,true),'resizable popup state missing')
assert(screen:find('self.popupW=clamp',1,true) and screen:find('480',1,true) and screen:find('520',1,true),'popup minimum-size guard missing')
assert(screen:find('function Screen:listViewportHeight()',1,true),'scroll viewport must follow resized height')
assert(screen:find('total-self:listViewportHeight()',1,true),'wheel scroll still uses fixed popup height')
assert(presenter:find('screen.popupW or 610,screen.popupH or 860',1,true),'presenter still uses fixed editor dimensions')
assert(presenter:find('graphicsEditorPopupResizeHandle',1,true),'resize handle missing')
assert(presenter:find('local labelW=math.max(142,math.min(206,r.w*.38))',1,true),'row content is not width-responsive')
print('PASS test_live_editor_responsive_window')
