local root=assert(arg[1])
local source=assert(io.open(root..'/components/footer.lua','rb')):read('*a')
assert(source:find('controllerFamily=="playstation"',1,true),'PlayStation family branch')
assert(source:find('controllerFamily=="xbox"',1,true),'Xbox family branch')
assert(source:find('controllerFamily=="nintendo"',1,true),'Nintendo family branch')
assert(source:find('leftshoulder="L1",rightshoulder="R1"',1,true),'PlayStation L1/R1 glyphs')
assert(source:find('leftshoulder="LB",rightshoulder="RB"',1,true),'Xbox LB/RB glyphs')
assert(source:find('leftshoulder="L",rightshoulder="R"',1,true),'Nintendo/handheld L/R glyphs')
print('round7 controller-family shoulder glyph tests passed')
