local root=assert(arg[1],"UI root required")
local function loadAt(path)local chunk,err=loadfile(root.."/"..path);assert(chunk,err);return chunk()end
local T=loadAt("generated/themes.lua")
local function near(a,b)return math.abs(a-b)<0.00001 end
local function hex(c,h)
  h=h:gsub("#","")
  local vals={tonumber(h:sub(1,2),16)/255,tonumber(h:sub(3,4),16)/255,tonumber(h:sub(5,6),16)/255}
  assert(near(c[1],vals[1]) and near(c[2],vals[2]) and near(c[3],vals[3]),"expected #"..h)
end
assert(T.DEFAULT=="cream","Cream must remain the default")
assert(#T.ORDER==4,"exactly four product themes must be exposed")
assert(table.concat(T.ORDER,",")=="cream,graphite,purplenight,retro","theme order")
assert(T.themes.cream and T.themes.graphite and T.themes.purplenight and T.themes.retro,"four theme records")
assert(T.themes.purplenight.figmaMode=="Sombre","PurpleNight must map to the Figma Sombre mode")
hex(T.themes.cream.colors.canvas,"#F0E8D1")
hex(T.themes.graphite.colors.canvas,"#141311")
hex(T.themes.graphite.colors.focus,"#28C8E6")
hex(T.themes.purplenight.colors.canvas,"#0C0A1C")
hex(T.themes.purplenight.colors.focus,"#A08CF5")
hex(T.themes.retro.colors.canvas,"#FFFFFF")
hex(T.themes.retro.colors.mainCardHover,"#888888")
hex(T.themes.cream.colors.mainHeaderAccent,"#00748C")
hex(T.themes.graphite.colors.mainHeaderAccent,"#28C8E6")
hex(T.themes.purplenight.colors.mainHeaderAccent,"#00748C")
hex(T.themes.retro.colors.mainHeaderAccent,"#545454")
hex(T.themes.retro.colors.headerAccent,"#B4B4B4")

hex(T.themes.cream.screen.bagFocus,"#00748C")
hex(T.themes.graphite.screen.bagFocus,"#C29B4B")
hex(T.themes.purplenight.screen.bagFocus,"#00748C")
hex(T.themes.retro.screen.bagFocus,"#080808")
hex(T.themes.cream.screen.modsFocus,"#00748C")
hex(T.themes.purplenight.screen.modsFocus,"#00748C")
hex(T.themes.retro.screen.modsFocus,"#080808")
hex(T.themes.cream.screen.pcSelectedRail,"#00748C")
hex(T.themes.graphite.screen.pcSelectedRail,"#E5A000")
hex(T.themes.purplenight.screen.pcSelectedRail,"#00BBE2")
hex(T.themes.retro.screen.pcSelectedRail,"#545454")

hex(T.themes.cream.colors.headerFocus,"#00748C")
hex(T.themes.graphite.colors.headerFocus,"#C29B4B")
hex(T.themes.purplenight.colors.headerFocus,"#00748C")
hex(T.themes.retro.colors.headerFocus,"#B4B4B4")

hex(T.themes.cream.screen.optionsFocus,"#00748C")
hex(T.themes.graphite.screen.optionsFocus,"#9B7832")
hex(T.themes.purplenight.screen.optionsFocus,"#00748C")
hex(T.themes.retro.screen.optionsFocus,"#080808")
hex(T.themes.retro.screen.optionsCanvas,"#FFFFFF")
assert(T.themes.retro.fontFamily=="kanto_rework.pixelify_sans","Retro Pixelify Sans routing")
for _,id in ipairs(T.ORDER) do assert(id~="rouge","technical Rouge mode must not be exposed") end
print("Theme token tests passed")
