local root=assert(arg[1],'root path required')
local s=assert(io.open(root..'/ui/naming_presenter.lua','rb')):read('*a')
local main=assert(io.open(root..'/main.lua','rb')):read('*a')
local corePath=root..'/../kanto_rework_core/core/text_input.lua';local probe=io.open(corePath,'rb');if not probe then corePath=root..'/../core/core/text_input.lua' else probe:close() end
local core=assert(io.open(corePath,'rb')):read('*a')
assert(s:find("require('src.ui.NamingScreen')",1,true),'KRS naming presenter wraps official NamingScreen')
assert(s:find("'PLAYER NAME','PLAYER'",1,true) and s:find("'RIVAL NAME','RIVAL'",1,true),'player and rival naming contexts are differentiated')
assert(s:find('state:grid()',1,true) and s:find('state.row,state.col',1,true),'controller/touch use engine-owned naming grid coordinates')
assert(s:find('runtime.namingPresetHover',1,true),'mouse hover is tracked independently from keyboard/controller focus')
assert(s:find('menu.__krsSelectedIndex',1,true),'persistent Selected state is distinct from focus')
assert(s:find('runtime.namingPresetPressed',1,true),'Pressed feedback has its own transient state')
assert(s:find('local focused=',1,true) and s:find('local isSelected=',1,true) and s:find('local isHover=',1,true) and s:find('local isPressed=',1,true),'Default/Hover/Focused/Selected/Pressed are separate presenter states')
assert(main:find('NativeNamingScreen.update=function(state,dt)',1,true),'Wide controller back bridge is installed')
assert(main:find('#(state.glyphs or {})==0',1,true) and main:find('state:enter();return',1,true),'B returns to preset chooser only when the text field is empty')
assert(core:find('key=="backspace"',1,true) and core:find('table.remove(state.glyphs)',1,true),'keyboard Backspace deletes through shared KRS text input')
assert(core:find('key=="return" or key=="kpenter"',1,true) and core:find('state:confirm()',1,true),'keyboard Enter confirms through official NamingScreen')
assert(core:find('key=="escape"',1,true) and core:find('state:enter()',1,true),'keyboard Escape returns to the preset step')
print('KRS player/rival naming presenter/input tests passed')
