local screen=assert(io.open('../screens/graphics_editor.lua','rb')):read('*a')
local battle=assert(io.open('../ui/battle_presenter.lua','rb')):read('*a')
local layout=assert(io.open('../runtime/battle_layout_config.lua','rb')):read('*a')
assert(layout:find("move_menu={x=0,y=0,scale=100}",1,true),'move-menu layout scale default missing')
assert(screen:find("id='ui.move_menu'",1,true) and screen:find('MOVE SELECTION + DESCRIPTION',1,true),'move-menu editor position control missing')
assert(screen:find("id='ui.move_menu.scale'",1,true) and screen:find("label='MOVE MENU SCALE'",1,true),'move-menu independent scale control missing')
assert(screen:find("id='ui.move_menu.reset'",1,true),'move-menu reset missing')
assert(battle:find("if spec.uiTarget=='move_menu' then",1,true),'editor preview must render move-menu context when selected')
assert(battle:find("local scale=clamp(tonumber(offset and offset.scale) or 100,50,150)",1,true),'moveDock must consume persisted scale')
assert(battle:find("runtime.battleRects[i]={x=baseX+(r.x-baseX)*factor",1,true),'move pointer hit rectangles must use the same scale transform')
assert(battle:find("moveDock(D,m,c,game,s,uiLayout.move_menu)",1,true),'production move menu does not consume saved layout')
assert(battle:find("D.text(runtime,m,sel.description",1,true),'move description must remain inside the real moveDock renderer')
assert(battle:find("{id='move_menu',component='battle.moves',renderer=moveDock,movable=true}",1,true),'live contract must advertise move-menu movement')
print('PASS test_live_editor_move_menu')
