local screen=assert(io.open('../screens/graphics_editor.lua','rb')):read('*a')
local presenter=assert(io.open('../ui/menu_presenter.lua','rb')):read('*a')
assert(not screen:find('editingNumeric',1,true),'free numeric edit state must be removed')
assert(not screen:find('replaceOnType',1,true),'typed-digit replacement path must be removed')
assert(not screen:find('TYPE VALUE',1,true),'numeric-entry affordance must be removed')
assert(screen:find("SLIDER · ←/→ STEP · SHIFT/SELECT = FINE",1,true),'slider needs discoverable stepped/fine adjustment')
assert(screen:find('local step=(keyFine or padFine) and 1 or 5',1,true),'normal/fine slider precision levels missing')
assert(presenter:find("local value=tostring(math.floor((row.value or 0)+.5))",1,true),'numeric value may remain display-only')
print('PASS test_live_editor_no_numeric_entry')
