local screen=assert(io.open('../screens/graphics_editor.lua','rb')):read('*a')
local battle=assert(io.open('../ui/battle_presenter.lua','rb')):read('*a')
local layout=assert(io.open('../runtime/battle_layout_config.lua','rb')):read('*a')
assert(layout:find("player_frame={x=0,y=0,scale=100}",1,true),'player HUD UI-owned default/scale missing')
assert(screen:find("id='ui.player_frame'",1,true),'player HUD editor row missing')
assert(screen:find("id='ui.player_frame.scale'",1,true) and screen:find("label='PLAYER INFO BOX SCALE'",1,true),'player HUD scale control missing')
assert(screen:find("id='ui.player_frame.reset'",1,true),'player HUD reset missing')
assert(battle:find("hudWithLayout(D,m,c,game,playerBattler,uiLayout,'player_frame',0,playerBaseY,620,180,false)",1,true),'preview player HUD must start at left edge and use real renderer')
assert(battle:find("hudWithLayout(D,m,c,game,s.player,uiLayout,'player_frame',0,playerY,620,180,false)",1,true),'production player HUD must use same left-anchor transform')
assert(battle:find("local pivotX=enemy and (x+w) or x",1,true),'player HUD scale must pivot on its left edge')
assert(battle:find("{id='player_frame',component='battle.hud.player',renderer=hud,movable=true}",1,true),'live contract must advertise player HUD movement')

assert(screen:find('function Screen:uiMovementLimits',1,true) and screen:find('1920-((tonumber(bounds.x)',1,true) and screen:find('1080-((tonumber(bounds.y)',1,true),'HUD movement must derive from actual preview bounds')
assert(not screen:find('trainer and 0 or -960',1,true) and not screen:find('trainer and 86 or -540',1,true),'Candidate.5 generic half-screen UI clamp must be removed')
print('PASS test_live_editor_player_hud')
