local screen=assert(io.open('../screens/graphics_editor.lua','rb')):read('*a')
local battle=assert(io.open('../ui/battle_presenter.lua','rb')):read('*a')
local layout=assert(io.open('../runtime/battle_layout_config.lua','rb')):read('*a')
assert(layout:find("opponent_frame={x=0,y=0,scale=100}",1,true),'enemy HUD UI-owned default/scale missing')
assert(screen:find("id='ui.opponent_frame'",1,true),'enemy HUD editor row missing')
assert(screen:find("id='ui.opponent_frame.scale'",1,true) and screen:find("label='ENEMY INFO BOX SCALE'",1,true),'enemy HUD scale control missing')
assert(screen:find("target='opponent_frame'",1,true),'enemy HUD target not explicit')
assert(screen:find('function Screen:nudgeUi',1,true),'UI fine/coarse movement backend missing')
assert(screen:find('runtime.graphicsEditorUiBounds',1,true),'direct UI drag must consume real preview bounds')
assert(battle:find("hudWithLayout(D,m,c,game,enemyBattler,uiLayout,'opponent_frame',1300,140,620,180,true)",1,true),'editor preview must render enemy HUD from right-edge source base')
assert(battle:find("if showEnemyHud then hudWithLayout(D,m,c,game,s.enemy,uiLayout,'opponent_frame',1300,140,620,180,true) end",1,true),'production enemy HUD must use same scale/anchor transform')
assert(battle:find("local pivotX=enemy and (x+w) or x",1,true),'enemy HUD scale must pivot on its right edge')
assert(battle:find("{id='opponent_frame',component='battle.hud.opponent',renderer=hud,movable=true}",1,true),'live editor contract must advertise implemented enemy HUD movement')

assert(screen:find('function Screen:uiMovementLimits',1,true) and screen:find('1920-((tonumber(bounds.x)',1,true) and screen:find('1080-((tonumber(bounds.y)',1,true),'HUD movement must derive from actual preview bounds')
assert(not screen:find('trainer and 0 or -960',1,true) and not screen:find('trainer and 86 or -540',1,true),'Candidate.5 generic half-screen UI clamp must be removed')
print('PASS test_live_editor_enemy_hud')
