local root=assert(arg[1],"UI root required")
local f=assert(io.open(root.."/ui/native_presenter.lua","rb"));local source=f:read("*a");f:close()
local resolveAt=assert(source:find("local function resolveText",1,true),"text resolver is declared")
local machineAt=assert(source:find("local function machineModel",1,true),"machine model is declared")
assert(resolveAt<machineAt,"TM/HM descriptions use the lexically scoped text resolver")
assert(source:find("def.teaches",1,true),"Gen 2 TM/HM `teaches` mapping is supported")
assert(source:find("def.tmLabel",1,true),"Gen 2 TM/HM label is supported")
assert(source:find("runtime.Core.moveDescription",1,true),"shared ROM-aware move descriptions are used")
assert(source:find("machine.label..' · '",1,true),"TM/HM label includes the taught move name")
assert(source:find("if machine then return machine.description end",1,true),"TM/HM move copy remains authoritative over item fallback copy")
assert(source:find("'ACCURACY',accuracy and accuracy>0 and (accuracy..'%')",1,true),"machine accuracy is displayed as a percentage")
print("Bag TM/HM move-name, description and stat regression tests passed")
