local root=assert(arg[1],'root path required')
local s=assert(io.open(root..'/ui/native_presenter.lua','rb')):read('*a')
assert(s:find('local function isShopRoot(state)',1,true),'shop root semantic detector exists')
assert(s:find("label=='BUY'",1,true) and s:find("label=='SELL'",1,true) and s:find("label=='QUIT'",1,true),'shop root detects official BUY/SELL/QUIT popup')
assert(s:find('local function drawShopRoot(game,m,c,state)',1,true),'KRS shop root presenter exists')
assert(s:find('or isShopRoot(state)',1,true),'shop root is owned by native presenter')
assert(s:find('if isShopRoot(top) then return drawShopRoot',1,true),'shop root is rendered by KRS')
assert(s:find("'CONFIRM PURCHASE?'",1,true) and s:find("local labels={'YES','NO'}",1,true),'purchase confirmation ChoiceBox is rendered as KRS UI')
assert(s:find('runtime.nativeChoiceRects',1,true),'shop confirmation exposes pointer/touch hit targets')
print('Poké Mart root + transaction KRS popup tests passed')
