local root=assert(arg[1],'root required')
local src=assert(io.open(root..'/ui/menu_presenter.lua','rb')):read('*a')
local layout=assert(io.open(root..'/ui/mod_info_layout.lua','rb')):read('*a')
assert(not src:find('infoBody={x=info.x,y=info.y+300',1,true),'preview must not create a smaller pseudo-panel with a second fixed top offset')
assert(src:find('infoLayoutOpts={topInset=(pr.y+pr.h+16)-info.y}',1,true),'preview and metadata share one outer-panel coordinate system')
assert(src:find('drawResponsiveModInfo(runtime,m,colors,screen,info,ctx,infoLayoutOpts)',1,true),'responsive info receives the real panel bounds')
assert(layout:find('math.min(maxCardH',1,true),'card height is hard-capped by available outer-panel height')
assert(layout:find('math.min(minCardH,maxCardH)',1,true),'canonical minimum cannot exceed available height')
print('Mod Manager preview/container contract tests passed')
