local root=assert(arg[1],'root required')
local f=assert(io.open(root..'/ui/battle_presenter.lua','rb'));local s=f:read('*a');f:close()
assert(not s:find("D.text(runtime,m,'START MENU'",1,true),'battle header removes START MENU')
assert(s:find('decorateAnimationAnchors',1,true) and s:find('allCombatants',1,true),'battle animation targeting has semantic live-anchor resolver')
local pSprites=assert(s:find('local visualBounds=drawSprites',1,true))
local pBack=assert(s:find("externalBattleAnimLayer(game,m,'back',visualBounds)",1,true))
local pFront=assert(s:find("externalBattleAnimLayer(game,m,'front',visualBounds)",1,true))
local pHud=assert(s:find("if showEnemyHud then hudWithLayout(D,m,c,game,s.enemy,uiLayout,'opponent_frame'",1,true))
local pShell=assert(s:find('shell(D,m,c,game,s);footer(game,m,c,prompts)',1,true))
assert(pSprites<pBack and pBack<pFront and pFront<pHud and pHud<pShell,'battle order is background/sprites/effects/HUD/chrome')
assert(s:find('fittingTextSize',1,true) and not s:find("D.clipText(runtime,m,label,x+156,y-11,180",1,true),'trainer identity no longer uses fixed ellipsis clip')
assert(s:find('1+4*pct',1,true),'Live size mapping is native 1x through 5x')
print('Battle post-test compositor/targeting contract tests passed')
