local root=assert(arg[1],"UI root required")
local factory=assert(loadfile(root.."/components/modular_overlays.lua"))()
local Overlay=factory({Core={},Palette={},PartyAdapter={},TypeIcon={},Models={},mod={},runtime={}})
local cream=Overlay._themeStyle({themeId="cream"},1)
local graphite=Overlay._themeStyle({themeId="graphite"},1)
local purple=Overlay._themeStyle({themeId="purplenight"},1)
local retro=Overlay._themeStyle({themeId="retro"},1)
assert(cream.radius==16 and graphite.radius==14 and purple.radius==18 and retro.radius==10,"each theme owns overlay chrome geometry")
assert(retro.border>=2,"Retro overlay chrome keeps a crisp pixel-weight border")
local f=assert(io.open(root.."/components/modular_overlays.lua","rb"));local source=f:read("*a");f:close()
assert(source:find("colors.inverse",1,true),"overlay headers use the selected theme structural rail")
assert(source:find("colors.headerAccent",1,true),"overlay headers use the selected theme accent")
assert(source:find("colors.structureText",1,true),"overlay title text follows the selected theme")
print("Theme-adaptive modular overlay chrome tests passed")
