local s=assert(io.open('screens/title_screen.lua','rb')):read('*a')
assert(s:find('self.inner:updateSequence()',1,true),'Yellow native cinematic timeline is advanced in Wide KRS')
assert(s:find('self.inner:updateBlink()',1,true),'Yellow Pikachu blink timeline remains active')
assert(not s:find('if self.nativeBackdrop then return self.inner:update(dt)',1,true),'Wide Yellow does not delegate input to native TitleState')
assert(s:find('assets/title/title_yellow.png',1,true),'Yellow resolves the supplied authored Wide start artwork')
assert(s:find('nativeBackdrop=version=="unknown"',1,true),'Yellow no longer uses the vanilla title as its primary Wide backdrop')
local presenter=assert(io.open('ui/menu_presenter.lua','rb')):read('*a')
assert(presenter:find('screen.version=="yellow" and screen.inner and not screen.image',1,true),'engine-imported Yellow pieces are fallback-only when authored art fails to load')
print('Yellow title timeline tests passed')
