local root=assert(arg[1],"root path required")
local function read(path)
  local file=assert(io.open(root.."/"..path,"rb"))
  local value=file:read("*a");file:close();return value
end
local function check(value,label)if not value then error(label or "check failed",2)end end

local presenter=read("ui/party_presenter.lua")
local controller=read("ui/party_controller.lua")
local layout=read("ui/party_layout.lua")
local menuPresenter=read("ui/menu_presenter.lua")
local nativePresenter=read("ui/native_presenter.lua")
local main=read("main.lua")
local saveSlots=read("screens/save_slots.lua")
local manifest=read("metadata/legacy_manifest.json")
local activeManifest=io.open(root.."/manifest.json","rb")

check(manifest:find('"version": "0.8.54"',1,true),"UI internal diagnostic version preserved")
check(activeManifest==nil,"internal UI module has no native manifest in Candidate")
check(presenter:find('runtime.fontFamily',1,true),"Party family uses shared typography")
check(presenter:find('"TEAM FORMATION"',1,true),"Figma Party hierarchy")
check(presenter:find('"DETERMINANT VALUES (DV) ★"',1,true),"full DV tab label")
check(presenter:find('display=display.." / 15"',1,true),"DV values include cap")
check(presenter:find('display=comma(v).." / 65,535"',1,true),"Stat Experience values include cap")
check(presenter:find('"★ PERFECT"',1,true),"perfect DV label")
check(presenter:find('label~="PHYSICAL" and label~="SPECIAL" and label~="STATUS"',1,true),"three move categories remain distinct")
check(presenter:find('"CATEGORY"',1,true),"learned-move comparison includes category")
check(presenter:find('for i=1,4 do',1,true),"active moves remain present")
check(not presenter:find('"IV/EV OVERLAYS"',1,true),"obsolete IV/EV future label removed")
check(not presenter:find('badge("FUTURE MOD",work.x',1,true),"obsolete learned-moves future badge removed")
check(presenter:find('frontSprite(game,p,r.x+150,r.y+60,200)',1,true),"Party detail sprite uses restored scale")
check(presenter:find('frontSprite(game,p,left.x+66,left.y+70,200)',1,true),"Summary sprite uses restored scale")
check(presenter:find('partyIcon(game,p,left.x+70,left.y+40,240)',1,true),"Moves identity uses the compact two-frame icon path")
check(presenter:find('assets/runtime/party_balls/',1,true),"canonical Figma party balls are embedded")
check(presenter:find('rect("fill",x,y,116,32',1,true),"move category badge has safe text padding")
check(presenter:find('local function activeMoveHeaderLayout',1,true),"active move headline uses measured collision-safe layout")
check(presenter:find('local nameGap=math.max(8,math.min(16,round(width*.03)))',1,true),"move-to-badge gap stays between 8 and 16 px")
check(presenter:find('while size>26 and width>maxNameWidth do',1,true),"27-character move names retain a readable minimum headline size")
check(presenter:find('candidate.id==active.id',1,true),"active focus resolves learned-move detail")
check(controller:find('or hit(state,x,y,"learned_move") or hit(state,x,y,"active_move")',1,true),"learned moves receive pointer detail focus in every move phase")
check(controller:find('state.activeMoveFocus=r.index;state.learnedFocus=nil',1,true),"active focus resets stale learned detail")
check(layout:find('y=220+row*256',1,true),"Figma Party card rhythm")
check(layout:find('x=620+col*624',1,true),"Figma Party card columns")
check(menuPresenter:find('assets/menu/main/',1,true),"main menu uses the validated image-card assets")
check(menuPresenter:find('D.withRoundedClip',1,true),"main menu clips artwork through the Lua rounded frame")
check(menuPresenter:find('state=="selected"',1,true),"main menu exposes Selected state")
check(menuPresenter:find('state=="hover"',1,true),"main menu exposes Hover state")

check(presenter:find('local labels={"SWITCH","STATS","CANCEL"}',1,true),"battle party actions use one unified semantic popup")
check(presenter:find('local px,py,pw,ph=600,442,720,196',1,true),"battle party action popup is centered, not bottom-left")
check(nativePresenter:find("require('src.ui.PartyMenu')",1,true),"native item target PartyMenu is captured by KRS")
check(main:find("NativePartyMenu.update=function",1,true) and main:find("if action==\"up\" then return left end",1,true),"native battle switch popup maps keyboard/controller to horizontal KRS actions")
check(main:find('if state.pickOnly and not state.submenu then',1,true) and main:find('PartyLayout.partyNeighbor(state.index or 1,direction,#party)',1,true),'Bag item target picker reuses canonical KRS Party two-column navigation')
check(nativePresenter:find("CHOOSE A POKÉMON",1,true),"healing target selection receives a visible KRS party prompt")
check(nativePresenter:find("require('src.ui.MoveLearnMenu')",1,true) and nativePresenter:find('LEARN A MOVE',1,true),"move learning stays inside KRS presentation")
check(main:find("runtime.NativePresenter.handles(game,state)",1,true),"native MoveLearn/item TextBox and Choice chrome are suppressed while KRS presents them")
check(nativePresenter:find("which move",1,true) and nativePresenter:find('CHOOSE A MOVE',1,true),"Ether/PP move targeting stays inside KRS")
check(saveSlots:find('confirmSave=true',1,true) and saveSlots:find("require('src.core.Sound').play(self.game.data,'Save')",1,true),"save slot requires confirmation and plays save feedback")

print("Pokémon menu fidelity contract passed")
