local root=assert(arg[1]);local main=assert(io.open(root..'/main.lua','rb')):read('*a');local party=assert(io.open(root..'/ui/party_controller.lua','rb')):read('*a');local mods=assert(io.open(root..'/screens/mods_menu.lua','rb')):read('*a');local editor=assert(io.open(root..'/screens/graphics_editor.lua','rb')):read('*a');local battle=assert(io.open(root..'/ui/battle_presenter.lua','rb')):read('*a');local presenter=assert(io.open(root..'/ui/menu_presenter.lua','rb')):read('*a')
assert(main:find("pad='leftshoulder'",1,true) and main:find("pad='rightshoulder'",1,true),'shoulder shortcuts use standardized SDL buttons')
assert(main:find("id='UI_SUBMENU_PREV'",1,true) and main:find("id='UI_SUBMENU_NEXT'",1,true),'bumper actions are rebindable Core actions')
assert(party:find('function controller:cycleSubmenu',1,true) and party:find('state.battleMode',1,true),'Party shoulder navigation excludes battle collisions')
assert(mods:find('function Screen:cycleTab',1,true),'Mod Manager tabs support bumpers')
assert(editor:find("scope=liveBattle and 'local' or 'global'",1,true) and editor:find("scope=='local'",1,true) and editor:find('NEW LOCAL DRAFT',1,true),'Graphics editor implements Global/Local and non-persistent local draft seeding')
assert(editor:find('sliderDrag',1,true) and editor:find('spriteDrag',1,true) and editor:find('function Screen:saveChanges()',1,true) and editor:find('DISCARD UNSAVED',1,true),'editor uses live dirty state with explicit save/discard persistence')
assert(editor:find("generationValues(side,self[role..'Species'],'animated')",1,true) and editor:find('disabled=#modes<=1',1,true),'unavailable animation modes are not offered as selectable choices')
assert(not editor:find('editingNumeric',1,true) and not editor:find('replaceOnType',1,true),'Live Editor no longer exposes free numeric slider entry')
assert(presenter:find("tostring(ctx.option.id)=='ui_theme'",1,true) and presenter:find('main_card_pokemon_hover.png',1,true) and presenter:find('VISUAL PREVIEW',1,true),'Mod Manager exposes contextual Graphics and UI-theme visual previews')
assert(battle:find('function P.drawGraphicsPreview',1,true) and battle:find("pipeline='battle_presenter.shared'",1,true) and battle:find('drawBackdrop(D,m,c,backdrop,sceneConfig.background)',1,true),'preview reuses BattlePresenter pipeline')
print('round7 shoulder/editor contract tests passed')
