local screen=assert(io.open('../screens/graphics_editor.lua','rb')):read('*a')
local battle=assert(io.open('../ui/battle_presenter.lua','rb')):read('*a')
local cfg=assert(io.open('../../graphics/editor_config.lua','rb')):read('*a')
assert(screen:find("id='background.scale'",1,true),'background zoom control missing')
assert(screen:find("id='background.offset'",1,true),'background offset control missing')
assert(screen:find("id='background.reset'",1,true),'background reset missing')
assert(screen:find('function Screen:nudgeBackground',1,true),'background fine/coarse nudge missing')
assert(cfg:find("background={scale=100,offsetX=0,offsetY=0}",1,true),'safe background defaults missing')
assert(battle:find('normalizedBackdropTransform',1,true),'background transform normalization missing')
assert(battle:find('local dw,dh=1920*t.scale,950*t.scale',1,true),'background must use one uniform scale for both axes')
assert(not battle:find('scaleX',1,true) and not battle:find('scaleY',1,true),'non-uniform background scale must not exist')
assert(battle:find('transformBackdropPoint',1,true),'battle circle anchors must follow framing transform')
assert(battle:find('groundAnchors={player=transformBackdropPoint',1,true),'production battler grounding must consume transformed anchors')
print('PASS test_live_editor_background_controls')
