local screen=assert(io.open('../screens/graphics_editor.lua','rb')):read('*a')
local battle=assert(io.open('../ui/battle_presenter.lua','rb')):read('*a')
local layout=assert(io.open('../runtime/battle_layout_config.lua','rb')):read('*a')
assert(layout:find("command_list={x=0,y=0,scale=100}",1,true),'action menu layout scale default missing')
for _,id in ipairs({'command_fight','command_pokemon','command_bag','command_run'}) do assert(layout:find(id.."={x=0,y=0}",1,true),id..' independent layout default missing') end
assert(screen:find("id='ui.command_list'",1,true) and screen:find("id='ui.command_list.scale'",1,true) and screen:find("id='ui.command_list.reset'",1,true),'action menu editor group position/scale/reset controls missing')
assert(screen:find("local commandLabels={fight='FIGHT',pokemon='POKéMON',bag='BAG',run='RUN'}",1,true),'independent command labels missing')
assert(screen:find("local target='command_'..commandId",1,true) and screen:find("kind='ui_position',id='ui.'..target",1,true) and screen:find("id='ui.'..target..'.reset'",1,true),'independent command position/reset controls missing')
assert(screen:find("if focused and focused.target then self.uiTarget=focused.target",1,true),'keyboard/controller focus must switch real preview phase/target')
assert(screen:find("if row and row.target then self.uiTarget=row.target",1,true),'pointer focus must switch real preview phase/target')
assert(battle:find("if spec.uiTarget~='move_menu' then",1,true),'editor preview must show real command choices by default outside moveSelect context')
assert(battle:find("local function commandBlock",1,true) and battle:find("target='command_'..semantic",1,true) and battle:find("commandCard(D,tm,c,d[1],d[2],x,yy,w,h",1,true),'preview/production must use real commandCard renderer with per-choice transforms')
assert(battle:find("boundsByTarget[target]=r",1,true),'preview must expose actual per-choice command bounds for direct drag')
assert(battle:find("local _,rects=commandBlock(D,m,c,defs,s.menuIndex,uiLayout);runtime.battleRects=rects",1,true),'production action menu must consume same transform and scaled pointer bounds')
assert(battle:find("{id='command_list',component='battle.commands',renderer=commandCard,movable=true}",1,true),'live contract does not advertise action menu movement')
print('PASS test_live_editor_action_menu')
