local screen=assert(io.open('../screens/graphics_editor.lua','rb')):read('*a')
local presenter=assert(io.open('../ui/menu_presenter.lua','rb')):read('*a')
local battle=assert(io.open('../ui/battle_presenter.lua','rb')):read('*a')
assert(screen:find("small='DIGLETT'",1,true) and screen:find("medium='PIKACHU'",1,true) and screen:find("large='SNORLAX'",1,true),'three documented preview presets exist')
assert(screen:find("key=='tab'",1,true) and screen:find('gridEnabled',1,true),'TAB exclusively toggles debug grid in editor key handler')
assert(screen:find("'debug.z'",1,true) and screen:find('N/A · RENDER ORDER ONLY',1,true),'Z is visibly disabled instead of faked')
assert(presenter:find("st=='focus'",1,true) and presenter:find("st=='hover'",1,true) and presenter:find('PRESSED',1,true) and presenter:find('SELECTED',1,true) and presenter:find('DISABLED',1,true),'Live editor exposes distinct visual state labels/shapes')
assert(battle:find('shell(D,m,c,game',1,true) and battle:find("if spec.grid then",1,true),'preview reuses real battle header and supports renderer-coordinate grid')
assert(battle:find('top={x=gx',1,true) and battle:find('feet={x=gx',1,true),'preview returns semantic live anchors')
print('PASS test_live_graphics_editor_post_test')
