local root=assert(arg[1],'root path required')
local p=assert(io.open(root..'/ui/party_adapter.lua','rb')):read('*a')
local m=assert(io.open(root..'/ui/menu_presenter.lua','rb')):read('*a')
local g=assert(io.open(root..'/runtime/graphics.lua','rb')):read('*a')
assert(p:find('"party.icon"',1,true),'Party icon component requests party.icon Graphics context')
assert(m:find("'pc.icon'",1,true) and m:find('runtime.Graphics.draw',1,true),'PC presentation requests the animated two-frame pc.icon Graphics context')
assert(g:find("filter=asset.filter=='linear' and 'linear' or 'nearest'",1,true),'Graphics consumer preserves nearest for pixel-art assets')
assert(g:find('frameCount',1,true) and g:find('newQuad',1,true),'Graphics consumer slices animated sprite sheets')
assert(not m:find('local function pcImage',1,true),'PC compact slots do not pass through front-sprite Real Size presentation')
print('Party/PC KRS Graphics context tests passed')
