local battle=dofile('generated/battle_art_index.lua')
local gen5=dofile('generated/trainer_art_gen5_index.lua')
local make=dofile('trainer_art.lua')
local art=make({battleIndex=battle,gen5Index=gen5,assetPath=function(p) return '/mod/'..p end})
local function eq(a,b,msg) assert(a==b,(msg or 'mismatch')..': '..tostring(a)..' ~= '..tostring(b)) end
local brock=art.resolve('gen5',{oppClass='OPP_BROCK',partyIndex=1})
eq(brock.resolvedSource,'gen5');eq(brock.animated,true);assert(#brock.durationsMs==brock.frameCount)
local agatha=art.resolve('gen5',{oppClass='OPP_AGATHA',partyIndex=1})
eq(agatha.resolvedSource,'gen3','Gen5 missing class falls to Gen3');eq(agatha.fallback,true)
local gen2=art.resolve('gen2',{oppClass='OPP_MISTY'})
eq(gen2.resolvedSource,'gen2');eq(gen2.animated,false)
local rom=art.resolve('rom',{oppClass='OPP_BLAINE'})
eq(rom.native,true);eq(rom.resolvedSource,'rom')
local rocket=art.resolve('gen5',{oppClass='OPP_ROCKET',partyIndex=1})
eq(rocket.slug,'rocket');eq(rocket.resolvedSource,'gen3')
local jj=art.resolve('gen5',{oppClass='OPP_ROCKET',partyIndex=42})
eq(jj.slug,'jessie-james');eq(jj.resolvedSource,'gen3')
local sources=table.concat(art.sources,',')
assert(not sources:find('gen4',1,true),'Gen4 trainer source must not be exposed')
print('trainer art resolution: PASS')
