local m=assert(io.open('main.lua','rb')):read('*a')
assert(m:find("context=='party.icon'",1,true),'party icon context is explicit')
assert(m:find("context=='pc.icon'",1,true),'pc icon context is explicit')
assert(m:find("context=='save.icon'",1,true),'save icon context is explicit')
assert(m:find("context=='intro.pokemon'",1,true),'intro Pokemon context is explicit')
assert(m:find('frameCount=2',1,true) and m:find('frameWidth=32',1,true),'menu icons expose two 32px frames')
assert(m:find('frameDuration=0.15',1,true) and m:find('frameDurationMs=150',1,true),'menu icon cadence is the fixed 150ms-per-frame presentation rule')
assert(m:find("context=='party.preview' or context=='summary.preview' or context=='pokedex.preview'",1,true),'large front-art contexts are restricted to Party active, Summary and Pokédex')
assert(m:find("context=='moves.icon'",1,true) and m:find("context=='main_menu.icon'",1,true),'compact menu contexts resolve through icons')
assert(m:find('presentationScale=nativeTrainer and 0.5 or nil',1,true),'Red/Blue intro artwork carries validated presentation metadata')
assert(m:find("filter='nearest'",1,true),'pixel assets use nearest filtering')
assert(m:find("'world.tod'",1,true) and m:find("'render.compose'",1,true),'time system uses public Gen1Recomp TOD and composition seams')
print('graphics registry contract tests passed')
